# Generated by Django 5.2.12 on 2026-03-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apreensao',
            name='autorizacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apreensao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apreensao',
            name='peso',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='apreensao',
            name='status',
            field=models.CharField(default='conferencia', max_length=50),
        ),
        migrations.AlterField(
            model_name='historico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
