# Generated by Django 6.0.3 on 2026-03-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custodia", "0007_historicalapreensao_historicalloteincineracao"),
    ]

    operations = [
        migrations.AddField(
            model_name="apreensao",
            name="natureza",
            field=models.CharField(
                choices=[
                    ("DROGAS", "Tráfico / Posse de Drogas"),
                    ("AMEACA", "Ameaça / Desobediência / Injúria"),
                    ("SOM", "Perturbação do Sossego (Som)"),
                    ("OUTROS", "Outros Tipos de Termos"),
                ],
                db_index=True,
                default="DROGAS",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="apreensao",
            name="tem_apreensao",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalapreensao",
            name="natureza",
            field=models.CharField(
                choices=[
                    ("DROGAS", "Tráfico / Posse de Drogas"),
                    ("AMEACA", "Ameaça / Desobediência / Injúria"),
                    ("SOM", "Perturbação do Sossego (Som)"),
                    ("OUTROS", "Outros Tipos de Termos"),
                ],
                db_index=True,
                default="DROGAS",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="historicalapreensao",
            name="tem_apreensao",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="apreensao",
            name="peso",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apreensao",
            name="substancia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="apreensao",
            name="unidade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="historicalapreensao",
            name="peso",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalapreensao",
            name="substancia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalapreensao",
            name="unidade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
