# Generated by Django 6.0.3 on 2026-03-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodia', '0008_apreensao_natureza_apreensao_tem_apreensao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apreensao',
            name='substancia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapreensao',
            name='substancia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
