# Generated by Django 6.0.3 on 2026-04-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custodia", "0009_alter_apreensao_substancia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apreensao",
            name="arquivo_pdf",
            field=models.FileField(
                blank=True, editable=False, null=True, upload_to="laudos_pdf/"
            ),
        ),
        migrations.AlterField(
            model_name="historicalapreensao",
            name="arquivo_pdf",
            field=models.TextField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
    ]
