# Generated by Django 6.0.3 on 2026-05-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custodia", "0015_add_numero_recibo"),
    ]

    operations = [
        migrations.AddField(
            model_name="apreensao",
            name="assinatura_base64",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apreensao",
            name="token_assinatura",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="apreensao",
            name="token_expira_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalapreensao",
            name="assinatura_base64",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalapreensao",
            name="token_assinatura",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalapreensao",
            name="token_expira_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
