# Generated by Django 6.0.3 on 2026-05-26 01:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custodia", "0016_add_assinatura_eletronica"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalOficioPersonalizado",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("numero_oficio", models.IntegerField(blank=True, null=True)),
                ("ano_oficio", models.IntegerField(blank=True, null=True)),
                ("bou", models.CharField(blank=True, max_length=100, null=True)),
                ("assunto", models.CharField(max_length=200)),
                ("texto", models.TextField()),
                ("tratamento", models.CharField(max_length=100)),
                ("cargo_destinatario", models.CharField(max_length=100)),
                ("orgao_destino", models.CharField(max_length=200)),
                ("cidade_destino", models.CharField(max_length=100)),
                (
                    "data_criacao",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical oficio personalizado",
                "verbose_name_plural": "historical oficio personalizados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OficioPersonalizado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_oficio", models.IntegerField(blank=True, null=True)),
                ("ano_oficio", models.IntegerField(blank=True, null=True)),
                ("bou", models.CharField(blank=True, max_length=100, null=True)),
                ("assunto", models.CharField(max_length=200)),
                ("texto", models.TextField()),
                ("tratamento", models.CharField(max_length=100)),
                ("cargo_destinatario", models.CharField(max_length=100)),
                ("orgao_destino", models.CharField(max_length=200)),
                ("cidade_destino", models.CharField(max_length=100)),
                (
                    "data_criacao",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
