# Generated by Django 6.0.3 on 2026-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custodia", "0017_historicaloficiopersonalizado_oficiopersonalizado"),
    ]

    operations = [
        migrations.AddField(
            model_name="apreensao",
            name="rg",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="apreensao",
            name="unidade_origem",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalapreensao",
            name="rg",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicalapreensao",
            name="unidade_origem",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
