# Generated by Django 6.0.3 on 2026-03-10 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('natureza', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Apreensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.ocorrencia')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('tipo', models.CharField(choices=[('autor', 'Autor'), ('vitima', 'Vítima'), ('testemunha', 'Testemunha')], max_length=20)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.ocorrencia')),
            ],
        ),
    ]
